### ISSUE TITLE
Issue running Gradle plugin with Compose Screenshot 0.0.1-alpha07

### ISSUE THREAD

**Issue by Stew-Boling-Sense** [screenshotbot/screenshotbot-gradle-plugin#2]
Trying CI integration on a spike branch on Bitrise and getting the following errors

> Task :consumer:recordAndVerifyDebugScreenshotTestUploadSnapshots FAILED
[03:03:46] INFO : Screenshotbot SDK v2.8.13
Could not guess the main branch, please use --main-branch argument
Call to "OUTPUT-BACKTRACE-KEY"
Call to "OUTPUT-BACKTRACE"
Call to "(SUBFUNCTION 4 CALL-WITH-CLI-SENTRY)"
Call to "SIGNAL"
Call to "CONDITIONS-ERROR"
Call to "ERROR"
Call to "CACHE-MISS-FUNCTION"
Call to "TEMPLATED-METHOD-COMBINATION"
Call to "NEXT-METHOD-CALL-1"
Call to "(METHOD MAIN-BRANCH AROUND ENV-READER-RUN-CONTEXT)"
Call to "TEMPLATED-METHOD-COMBINATION"
Call to "CACHE-MISS-FUNCTION"
Call to "PARSE-ENVIRONMENT"
Call to "CALL-WITH-DEFAULTS"
Call to "%MAIN"
Call to "(SUBFUNCTION 1 MAIN)"
Call to "CALL-WITH-CLI-SENTRY"
Call to "CALL-WITH-SENTRY"
Call to "MAIN"
Call to "MAYBE-RYB-TOP-LEVEL"
Call to "PROCESS-SG-FUNCTION"
Call to "%%FIRST-CALL-TO-STACK"
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':common:dialog:recordAndVerifyDebugScreenshotTestUploadSnapshots'.
> Process 'command '/root/screenshotbot/recorder'' finished with non-zero exit value 1

Environment:
Bitrise
Screenshot Bot Gradle Plugin 1.14
Compose Screenshot Testing 0.0.1-alpha07
Gradle 8.10
Branch name: spike/ScreenshotBot

I can't find any documentation on setting the main branch name with the Gradle plugin

**Comment by tdrhq** [comment]
Good catch, let me make that configurable, I'll try to update that by EOD (New York time)

**Comment by tdrhq** [comment]
I've pushed a new version (1.15) that has a mainBranch argument, let me know if that works for you

**Comment by Stew-Boling-Sense** [comment]
Thank you, yep it is working great!
